### ISSUE TITLE
Error when running experiments

### ISSUE THREAD

**Issue by enricobottazzi** [hashcloak/flashbots-privacy#24]
`python3 experiment/run_experiment.py`

```
2024-08-21 10:13:59,638 - INFO - Executing repetition 0
2024-08-21 10:13:59,638 - INFO - Setting up SSL for 4 parties
2024-08-21 10:14:00,289 - INFO - Creating input file for party P0
2024-08-21 10:14:00,290 - INFO - Creating input file for party P1
2024-08-21 10:14:00,290 - INFO - Creating input file for party P2
2024-08-21 10:14:00,290 - INFO - Creating input file for party P3
2024-08-21 10:14:00,290 - INFO - Compiling MPC file mpc_shifting_knapsack/shifting_knapsack.mpc
2024-08-21 10:14:00,528 - INFO - Running protocol mascot.sh for algorithm mpc_shifting_knapsack/shifting_knapsack.mpc
Traceback (most recent call last):
  File "/Users/enricobottazzi/Developer/GitHub/flashbots-privacy/experiment/run_experiment.py", line 326, in <module>
    experiment.regular_run()
  File "/Users/enricobottazzi/Developer/GitHub/flashbots-privacy/experiment/run_experiment.py", line 76, in regular_run
    self.times.append(self.run_repetition(i))
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enricobottazzi/Developer/GitHub/flashbots-privacy/experiment/run_experiment.py", line 91, in run_repetition
    result = self.run_mpc_protocol()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enricobottazzi/Developer/GitHub/flashbots-privacy/experiment/run_experiment.py", line 191, in run_mpc_protocol
    run_mpc_result.check_returncode()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['env', 'PLAYERS=4', './Scripts/mascot.sh', 'shifting_knapsack-4-30-30']' returned non-zero exit status 1.
```

**Comment by Mikerah** [comment]
Hi Enrico, besides that python command, did you run anything else? I think our README might be underspecified.

**Comment by enricobottazzi** [comment]
Ok, I tried again from scratch and it worked now, I was probably doing something wrong yesterday 😅
Closing the issue
